model:
  base_learning_rate: 1.e-5
  target: video_refiner.models.diffusion.DiffusionEngine
  params:
    use_ema: False
    input_key: img_seq
    scale_factor: 0.18215
    disable_first_stage_autocast: True
    num_frames: &num_frames 25
    token_shape: [1, 18, 32, 18]
    slow_spatial_layers: True
    train_peft_adapters: False
    en_and_decode_n_samples_a_time: 1

    denoiser_config:
      target: video_refiner.modules.diffusionmodules.denoiser.Denoiser
      params:
        num_frames: *num_frames
        scaling_config:
          target: video_refiner.modules.diffusionmodules.denoiser_scaling.VScalingWithEDMcNoise

    network_config:
      target: video_refiner.modules.diffusionmodules.video_model.VideoUNet
      params:
        adm_in_channels: 768
        num_classes: sequential
        use_checkpoint: True
        in_channels: 8
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        spatial_transformer_attn_type: softmax-xformers
        extra_ff_mix_layer: True
        use_spatial_context: True
        merge_strategy: learned_with_images
        video_kernel_size: [ 3, 1, 1 ]
        add_lora: False
        action_control: False

    conditioner_config:
      target: video_refiner.modules.encoders.modules.GeneralConditioner
      params:
        emb_models:
          - input_key: cond_aug
            is_trainable: False
            ucg_rate: 0.0
            target: video_refiner.modules.encoders.modules.ConcatTimestepEmbedderND
            params:
              outdim: 256

          - input_key: fps_id
            is_trainable: False
            ucg_rate: 0.0
            target: video_refiner.modules.encoders.modules.ConcatTimestepEmbedderND
            params:
              outdim: 256

          - input_key: motion_bucket_id
            is_trainable: False
            ucg_rate: 0.0
            target: video_refiner.modules.encoders.modules.ConcatTimestepEmbedderND
            params:
              outdim: 256

          - input_key: cond_frames
            is_trainable: False
            ucg_rate: 0.0
            target: video_refiner.modules.encoders.modules.VideoPredictionEmbedderWithEncoder
            params:
              disable_encoder_autocast: True
              n_cond_frames: *num_frames
              n_copies: 1
              is_ae: True

              encoder_config:
                target: video_refiner.models.autoencoder.AutoencoderKLModeOnly
                params:
                  embed_dim: 4
                  monitor: val/rec_loss
                
                  ddconfig:
                    attn_type: vanilla-xformers
                    double_z: True
                    z_channels: 4
                    resolution: 256
                    in_channels: 3
                    out_ch: 3
                    ch: 128
                    ch_mult: [ 1, 2, 4, 4 ]
                    num_res_blocks: 2
                    attn_resolutions: [ ]
                    dropout: 0.0

                  loss_config:
                    target: torch.nn.Identity

    first_stage_config:
      target: video_refiner.models.autoencoder.AutoencodingEngine
      params:
        loss_config:
          target: torch.nn.Identity
        
        regularizer_config:
          target: video_refiner.modules.autoencoding.regularizers.DiagonalGaussianRegularizer
        
        encoder_config:
          target: video_refiner.modules.diffusionmodules.model.Encoder
          params:
            attn_type: vanilla
            double_z: True
            z_channels: 4
            resolution: 256
            in_channels: 3
            out_ch: 3
            ch: 128
            ch_mult: [ 1, 2, 4, 4 ]
            num_res_blocks: 2
            attn_resolutions: [ ]
            dropout: 0.0
        
        decoder_config:
          target: video_refiner.modules.autoencoding.temporal_ae.VideoDecoder
          params:
            attn_type: vanilla
            double_z: True
            z_channels: 4
            resolution: 256
            in_channels: 3
            out_ch: 3
            ch: 128
            ch_mult: [ 1, 2, 4, 4 ]
            num_res_blocks: 2
            attn_resolutions: [ ]
            dropout: 0.0
            video_kernel_size: [ 3, 1, 1 ]
    
    scheduler_config:
      target: video_refiner.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [ 1000 ]
        cycle_lengths: [ 10000000000000 ]
        f_start: [ 1.e-6 ]
        f_max: [ 1. ]
        f_min: [ 1. ]
    
    loss_fn_config:
      target: video_refiner.modules.diffusionmodules.loss.StandardDiffusionLoss
      params:
        use_additional_loss: True
        offset_noise_level: 0.02
        additional_loss_weight: 0.1
        num_frames: *num_frames

        sigma_sampler_config:
          target: video_refiner.modules.diffusionmodules.sigma_sampling.EDMSampling
          params:
            p_mean: 1.0
            p_std: 1.6
            num_frames: *num_frames

        loss_weighting_config:
          target: video_refiner.modules.diffusionmodules.loss_weighting.VWeighting

    sampler_config:
      target: video_refiner.modules.diffusionmodules.sampling.EulerEDMSampler
      params:
        num_steps: 15

        discretization_config:
          target: video_refiner.modules.diffusionmodules.discretizer.EDMDiscretization
          params:
            sigma_max: 700.0
        
        guider_config:
          target: video_refiner.modules.diffusionmodules.guiders.LinearPredictionGuider
          params:
            num_frames: *num_frames
            max_scale: 3.0
            min_scale: 1.5

    token_decoder_config:
      repo_id: turing-motors/Terra
      subfolder: lfq_tokenizer_B_256
